
#ifndef MTLC_INTRINSIC_H
#define MTLC_INTRINSIC_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
  MTLC_INTRINSIC_NONE = 0,
  MTLC_INTRINSIC_GPU_LOCAL_ID_X,
  MTLC_INTRINSIC_GPU_LOCAL_ID_Y,
  MTLC_INTRINSIC_GPU_LOCAL_ID_Z,
  MTLC_INTRINSIC_GPU_LOCAL_SIZE_X,
  MTLC_INTRINSIC_GPU_LOCAL_SIZE_Y,
  MTLC_INTRINSIC_GPU_LOCAL_SIZE_Z,
  MTLC_INTRINSIC_GPU_GROUP_ID_X,
  MTLC_INTRINSIC_GPU_GROUP_ID_Y,
  MTLC_INTRINSIC_GPU_GROUP_ID_Z,
  MTLC_INTRINSIC_GPU_NUM_GROUPS_X,
  MTLC_INTRINSIC_GPU_NUM_GROUPS_Y,
  MTLC_INTRINSIC_GPU_NUM_GROUPS_Z,
  MTLC_INTRINSIC_GPU_SUBGROUP_LOCAL_ID,
  MTLC_INTRINSIC_GPU_SUBGROUP_SIZE,
  MTLC_INTRINSIC_GPU_SUBGROUP_BROADCAST_U32,
  MTLC_INTRINSIC_GPU_SUBGROUP_BROADCAST_F32,
  MTLC_INTRINSIC_GPU_SUBGROUP_REDUCE_ADD_U32,
  MTLC_INTRINSIC_GPU_SUBGROUP_REDUCE_ADD_F32,
  MTLC_INTRINSIC_GPU_SUBGROUP_REDUCE_MIN_U32,
  MTLC_INTRINSIC_GPU_SUBGROUP_REDUCE_MIN_F32,
  MTLC_INTRINSIC_GPU_SUBGROUP_REDUCE_MAX_U32,
  MTLC_INTRINSIC_GPU_SUBGROUP_REDUCE_MAX_F32,
  MTLC_INTRINSIC_GPU_SUBGROUP_SCAN_INCLUSIVE_ADD_U32,
  MTLC_INTRINSIC_GPU_SUBGROUP_SCAN_INCLUSIVE_ADD_F32,
  MTLC_INTRINSIC_GPU_SUBGROUP_SCAN_EXCLUSIVE_ADD_U32,
  MTLC_INTRINSIC_GPU_SUBGROUP_SCAN_EXCLUSIVE_ADD_F32,
  MTLC_INTRINSIC_GPU_SUBGROUP_SHUFFLE_U32,
  MTLC_INTRINSIC_GPU_SUBGROUP_SHUFFLE_F32,
  MTLC_INTRINSIC_GPU_SUBGROUP_BALLOT_WORD,
  MTLC_INTRINSIC_GPU_SUBGROUP_ANY,
  MTLC_INTRINSIC_GPU_SUBGROUP_ALL,
  MTLC_INTRINSIC_GPU_WORKGROUP_BARRIER,
  MTLC_INTRINSIC_GPU_SQRT_F32,
  MTLC_INTRINSIC_GPU_RSQRT_F32,
  MTLC_INTRINSIC_GPU_ABS_F32,
  MTLC_INTRINSIC_GPU_SIN_F32,
  MTLC_INTRINSIC_GPU_COS_F32,
  MTLC_INTRINSIC_GPU_LOG_F32,
  MTLC_INTRINSIC_GPU_EXP_F32,
  MTLC_INTRINSIC_GPU_F16_BITS_TO_F32,
  MTLC_INTRINSIC_GPU_F32_TO_F16_BITS,

  MTLC_INTRINSIC_GPU_F32_FROM_BITS,
  MTLC_INTRINSIC_GPU_F32_TO_BITS,

  MTLC_INTRINSIC_GPU_DP4A_U32,
  MTLC_INTRINSIC_GPU_DP4A_S32,

  MTLC_INTRINSIC_GPU_DP2A_LO_U32,
  MTLC_INTRINSIC_GPU_DP2A_LO_S32,
  MTLC_INTRINSIC_GPU_DP2A_HI_U32,
  MTLC_INTRINSIC_GPU_DP2A_HI_S32,

  MTLC_INTRINSIC_GPU_PRMT_B32,

  MTLC_INTRINSIC_GPU_LOAD4_F32,
  MTLC_INTRINSIC_GPU_LOAD4_U32,
  MTLC_INTRINSIC_GPU_STORE4_F32,
  MTLC_INTRINSIC_GPU_STORE4_U32,

  MTLC_INTRINSIC_GPU_HADD2,
  MTLC_INTRINSIC_GPU_HMUL2,
  MTLC_INTRINSIC_GPU_HFMA2,
  MTLC_INTRINSIC_GPU_H2F_LO,
  MTLC_INTRINSIC_GPU_H2F_HI,
  MTLC_INTRINSIC_GPU_F2H2,
  MTLC_INTRINSIC_GPU_BF2F,
  MTLC_INTRINSIC_GPU_F2BF,
  MTLC_INTRINSIC_GPU_PRINT,
  MTLC_INTRINSIC_GPU_PRINT_I32,
  MTLC_INTRINSIC_GPU_PRINT_F32,
  MTLC_INTRINSIC_GPU_PRINT_2I32,
  MTLC_INTRINSIC_GPU_ASSERT,
  MTLC_INTRINSIC_GPU_ATOMIC_MIN_U32,
  MTLC_INTRINSIC_GPU_ATOMIC_MIN_U64,
  MTLC_INTRINSIC_GPU_ATOMIC_ADD_U32,
  MTLC_INTRINSIC_GPU_ATOMIC_ADD_U64,
  MTLC_INTRINSIC_GPU_ATOMIC_SUB_U32,
  MTLC_INTRINSIC_GPU_ATOMIC_SUB_U64,
  MTLC_INTRINSIC_GPU_ATOMIC_MAX_U32,
  MTLC_INTRINSIC_GPU_ATOMIC_MAX_U64,
  MTLC_INTRINSIC_GPU_ATOMIC_AND_U32,
  MTLC_INTRINSIC_GPU_ATOMIC_AND_U64,
  MTLC_INTRINSIC_GPU_ATOMIC_OR_U32,
  MTLC_INTRINSIC_GPU_ATOMIC_OR_U64,
  MTLC_INTRINSIC_GPU_ATOMIC_XOR_U32,
  MTLC_INTRINSIC_GPU_ATOMIC_XOR_U64,
  MTLC_INTRINSIC_GPU_ATOMIC_EXCHANGE_U32,
  MTLC_INTRINSIC_GPU_ATOMIC_EXCHANGE_U64,
  MTLC_INTRINSIC_GPU_ATOMIC_COMPARE_EXCHANGE_U32,
  MTLC_INTRINSIC_GPU_ATOMIC_COMPARE_EXCHANGE_U64,
  MTLC_INTRINSIC_GPU_ATOMIC_LOAD_U32,
  MTLC_INTRINSIC_GPU_ATOMIC_LOAD_U64,
  MTLC_INTRINSIC_GPU_ATOMIC_STORE_U32,
  MTLC_INTRINSIC_GPU_ATOMIC_STORE_U64,
  /* Transaction barriers and tensor-map tile loads (sm_90+, PTX 8.0+). */
  MTLC_INTRINSIC_GPU_MBARRIER_INIT,
  MTLC_INTRINSIC_GPU_MBARRIER_ARRIVE_EXPECT_TX,
  MTLC_INTRINSIC_GPU_MBARRIER_WAIT_PARITY,
  MTLC_INTRINSIC_GPU_FENCE_MBARRIER_INIT,
  MTLC_INTRINSIC_GPU_FENCE_PROXY_ASYNC,
  MTLC_INTRINSIC_GPU_TMA_LOAD_2D,
  MTLC_INTRINSIC_GPU_TENSORMAP_ACQUIRE,
  MTLC_INTRINSIC_KIND_COUNT
} MtlcIntrinsic;

#ifdef __cplusplus
}
#endif

#endif
