#ifndef MTLC_HOST_PREFIX_H
#define MTLC_HOST_PREFIX_H

#define memset mtlc_host_memset
#define memcpy mtlc_host_memcpy
#define memmove mtlc_host_memmove
#define memchr mtlc_host_memchr
#define memcmp mtlc_host_memcmp
#define strlen mtlc_host_strlen
#define strcmp mtlc_host_strcmp
#define strncmp mtlc_host_strncmp
#define strchr mtlc_host_strchr
#define strrchr mtlc_host_strrchr
#define strncpy mtlc_host_strncpy
#define strcpy mtlc_host_strcpy
#define strcat mtlc_host_strcat
#define strstr mtlc_host_strstr
#define strpbrk mtlc_host_strpbrk
#define strcasecmp mtlc_host_strcasecmp
#define strtok mtlc_host_strtok
#define strdup mtlc_host_strdup
#define strerror mtlc_host_strerror

#define malloc mtlc_host_malloc
#define calloc mtlc_host_calloc
#define realloc mtlc_host_realloc
#define free mtlc_host_free

#define stdin mtlc_host_stdin
#define stdout mtlc_host_stdout
#define stderr mtlc_host_stderr
#define fopen mtlc_host_fopen
#define fclose mtlc_host_fclose
#define fread mtlc_host_fread
#define fwrite mtlc_host_fwrite
#define fputs mtlc_host_fputs
#define puts mtlc_host_puts
#define fputc mtlc_host_fputc
#define putchar mtlc_host_putchar
#define getchar mtlc_host_getchar
#define fgets mtlc_host_fgets
#define fflush mtlc_host_fflush
#define ferror mtlc_host_ferror
#define fseek mtlc_host_fseek
#define ftell mtlc_host_ftell
#define _fseeki64 mtlc_host_fseeki64
#define _ftelli64 mtlc_host_ftelli64
#define rewind mtlc_host_rewind
#define setvbuf mtlc_host_setvbuf
#define fileno mtlc_host_fileno
#define isatty mtlc_host_isatty
#define _fileno mtlc_host_fileno
#define _isatty mtlc_host_isatty
#define remove mtlc_host_remove
#define access mtlc_host_access
#define _access mtlc_host_access
#define getcwd mtlc_host_getcwd
#define mkdir mtlc_host_mkdir
#define _mkdir mtlc_host_mkdir_one
#define gettimeofday mtlc_host_gettimeofday
#define readlink mtlc_host_readlink
#define realpath mtlc_host_realpath
#define stat mtlc_host_stat
#define unlink mtlc_host_unlink
#define _unlink mtlc_host_unlink
#define putenv mtlc_host_putenv
#define _putenv mtlc_host_putenv
#define system mtlc_host_system
#define popen mtlc_host_popen
#define pclose mtlc_host_pclose
#define _popen mtlc_host_popen
#define _pclose mtlc_host_pclose

#define printf mtlc_host_printf
#define fprintf mtlc_host_fprintf
#define vfprintf mtlc_host_vfprintf
#define sprintf mtlc_host_sprintf
#define snprintf mtlc_host_snprintf
#define vsnprintf mtlc_host_vsnprintf
#define sscanf mtlc_host_sscanf
#define vsscanf mtlc_host_vsscanf

#define atoi mtlc_host_atoi
#define atol mtlc_host_atol
#define atoll mtlc_host_atoll
#define atof mtlc_host_atof
#define strtod mtlc_host_strtod
#define strtoul mtlc_host_strtoul
#define strtoull mtlc_host_strtoull
#define strtoll mtlc_host_strtoll
#define _strtoi64 mtlc_host_strtoi64
#define _strtoui64 mtlc_host_strtoui64
#define qsort mtlc_host_qsort
#define bsearch mtlc_host_bsearch
#define srand mtlc_host_srand
#define rand mtlc_host_rand
#define getenv mtlc_host_getenv
#define clock mtlc_host_clock
#define abort mtlc_host_abort
#define exit mtlc_host_exit
#define _exit mtlc_host_immediate_exit

#define isspace mtlc_host_isspace
#define isalpha mtlc_host_isalpha
#define isalnum mtlc_host_isalnum
#define isdigit mtlc_host_isdigit
#define isxdigit mtlc_host_isxdigit
#define isupper mtlc_host_isupper
#define islower mtlc_host_islower
#define isprint mtlc_host_isprint
#define isgraph mtlc_host_isgraph
#define ispunct mtlc_host_ispunct
#define iscntrl mtlc_host_iscntrl
#define tolower mtlc_host_tolower
#define toupper mtlc_host_toupper
#define sqrtf mtlc_host_sqrtf
#define fabs mtlc_host_fabs
#define exp mtlc_host_exp
#define expf mtlc_host_expf
#define tanh mtlc_host_tanh
#define tanhf mtlc_host_tanhf

#define close mtlc_host_close
#define ioctl mtlc_host_ioctl
#define mmap mtlc_host_mmap
#define munmap mtlc_host_munmap
#define mprotect mtlc_host_mprotect
#define socket mtlc_host_socket
#define connect mtlc_host_connect
#define bind mtlc_host_bind
#define listen mtlc_host_listen
#define accept mtlc_host_accept
#define setsockopt mtlc_host_setsockopt
#define send mtlc_host_send
#define recv mtlc_host_recv
#define shutdown mtlc_host_shutdown
#define clock_gettime mtlc_host_clock_gettime
#define nanosleep mtlc_host_nanosleep
#define usleep mtlc_host_usleep
#undef htons
#undef ntohs
#undef htonl
#undef ntohl
#define htons mtlc_host_htons
#define ntohs mtlc_host_ntohs
#define htonl mtlc_host_htonl
#define ntohl mtlc_host_ntohl
#define inet_addr mtlc_host_inet_addr

#define __acrt_iob_func mtlc_host_iob_func
#define mettle_errno_location mtlc_host_errno_location
#define mettle_rt_startup mtlc_host_rt_startup
#define mettle_rt_getmainargs mtlc_host_rt_getmainargs
#define mettle_run_process mtlc_host_run_process
#define mettle_find_executable mtlc_host_find_executable
#define mettle_install_signal_handler mtlc_host_install_signal_handler
#define mettle_address_is_readable mtlc_host_address_is_readable
#define mettle_alloc_report mtlc_host_alloc_report
#define mettle_crash_write_stderr_bytes mtlc_host_crash_write_stderr_bytes
#define mettle_crash_write_stderr mtlc_host_crash_write_stderr
#define mettle_crash_heap_classifier mtlc_host_crash_heap_classifier
#define mettle_crash_set_heap_classifier mtlc_host_crash_set_heap_classifier
#define mettle_thread_create mtlc_host_thread_create
#define mettle_thread_wait mtlc_host_thread_wait
#define mettle_thread_close mtlc_host_thread_close
#define mettle_thread_current_id mtlc_host_thread_current_id
#define mettle_thread_sleep mtlc_host_thread_sleep
#define mettle_mutex_create mtlc_host_mutex_create
#define mettle_mutex_wait mtlc_host_mutex_wait
#define mettle_mutex_release mtlc_host_mutex_release
#define mettle_mutex_close mtlc_host_mutex_close
#define mettle_atomic_compare_exchange_i32 mtlc_host_atomic_compare_exchange_i32
#define mettle_atomic_exchange_i32 mtlc_host_atomic_exchange_i32
#define mettle_atomic_inc_i32 mtlc_host_atomic_inc_i32
#define mettle_atomic_dec_i32 mtlc_host_atomic_dec_i32
#define posix_get_errno mtlc_host_posix_get_errno
#define posix_yield mtlc_host_posix_yield
#define posix_cas_i32 mtlc_host_posix_cas_i32
#define posix_atomic_exchange_i32 mtlc_host_posix_atomic_exchange_i32
#define posix_atomic_add_i32 mtlc_host_posix_atomic_add_i32

#endif
